### ISSUE TITLE
Trailer Preview in Movie Card is cut off on Mobile

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-fe#121]
## Expected Behavior
Trailer Preview image should fit inside of the movie card when on mobile.

## Current Behavior
Half of the trailer image is being cut off.

## Possible Solution
Expanding the size of the card to be full screen will help, while also adjusting the parameters of the video embedding.

## Steps to Reproduce
1. Navigate to groa.us/explore (on mobile)
2. Select a movie to open the card.
3. Observe the trailer being cut off.

## Context (Environment)

This exclusively happens on mobile devices. On desktop the trailer displays fully. Additionally, the trailer is not cut off when you turn the mobile device horizontally.

**Comment by Steven-matos** [comment]
the issue was resolved on PR#[141](https://github.com/Lambda-School-Labs/Groa-fe/pull/141)
