### ISSUE TITLE
navigation bar on mobile wider than screen, 

### ISSUE THREAD

**Issue by azatecas** [Lambda-School-Labs/Groa-fe#152]
## Expected Behavior
when accessing the recommendation the content should fin into the width of the screen

## Current Behavior
![navscroll](https://user-images.githubusercontent.com/29685279/83183422-c291fb00-a0f5-11ea-8fa8-a4ff0d029b67.PNG)

when accessing the recommendations page, the navigation bar is too wide and overflows

## Possible Solution
make the title of recommendation page smaller with a width, 100% the width of the screen on mobile

## Steps to Reproduce
1. Navigate to dashboard on mobile
2. scroll to the right on mobile and you will see a huge gap
3. Observer the user is able to scroll horizontally when that isnt a feature

## Context (Environment)
mobile view on my xiaomi a2 lite screen

**Comment by jvillalp** [comment]
fixed on PR #155
