### ISSUE TITLE
onboarding start screen is not mobile friendly

### ISSUE THREAD

**Issue by azatecas** [Lambda-School-Labs/Groa-fe#153]
## Expected Behavior
when the user is new, and accessing it on mobile the on-boarding start screen displays with instructions to the user. the text should take the width of the screen

## Current Behavior
the text of the instructions only take 50% of the screen width and to the left on mobile screen

## Possible Solution
make the text container width 100% on mobile

## Steps to Reproduce
1. navigate to user_id/onboardingplatform on mobile
2. Observer the text taking 50% of screen width on mobile

## Context (Environment)
mobile phone only
![halftext](https://user-images.githubusercontent.com/29685279/83183245-81015000-a0f5-11ea-85e6-de6713f04f3f.PNG)

**Comment by jvillalp** [comment]
fixed on PR #155
