### ISSUE TITLE
Posters don't Load on Recommended/Ratings/Watchlist Pages

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-fe#72]
## Expected Behavior
Posters should populate for each movie on Recommended, Ratings, and Watchlist pages.

## Current Behavior
A placeholder image is loaded instead of the poster images.

## Possible Solution
Possibly due to pulls from the old DB. 

More likely due to calling the structure of the tables in the Old DB, but querying the new DB, since this issue started before the old DB was turned off.

## Steps to Reproduce
1. Navigate to https://www.groa.us/ratings
2. Observe no posters

## Context (Environment)

Can't confirm currently due to login page non-functional.

**Comment by Steven-matos** [comment]
fixes posters on watchlist and rating page
