### ISSUE TITLE
Very long movie titles break our card formatting

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-fe#81]
## Expected Behavior
Movie titles should not move the rating and add to watchlist buttons out of the movie card.

## Current Behavior
Movie titles move the rating and add to watchlist buttons out of the movie card.

## Possible Solution
Either truncate the movie title or constrict the percentage of the card it can occupy.

## Steps to Reproduce
1. Navigate to https://www.groa.us/explore
2. Search for "Can Heironymus Merkin Ever Forget Mercy Humppe and Find True Happiness?"
3. Observe formatting cuts off bottom of movie card.

## Context (Environment)

Not sure what the best approach is.
![longmovietitles](https://user-images.githubusercontent.com/7471385/80535187-66a94a80-896e-11ea-971a-f7ce6dd8c355.PNG)

**Comment by Steven-matos** [comment]
the fix for this was implemented in PR #83
