### ISSUE TITLE
Hamburger Menu doesn't collapse when you click on the page

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-fe#82]
## Expected Behavior
When the user clicks on the page (outside of the menu) the menu should collapse.

## Current Behavior
The menu stays exposed until the user selects the "in" arrow at the top of the menu.

## Possible Solution
Not sure.

## Steps to Reproduce
1. Navigate to https://www.groa.us/explore
2. Expand the hamburger menu.
3. Click on the page outside the hamburger menu
4. Observer the menu remains expanded.

## Context (Environment)

The menu that appears when you click the User icon on the right side of the page does disappear when you click anywhere else on the page.

**Comment by jvillalp** [comment]
solved issue with menu. It now closes when you tap on page. will create a pull request
